
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      # service name
      SERVICE: user-service
    steps:
    - name: checkout
      uses: action/checkout@v2
      with:
         fetch-dept: 0
    - uses: paulhatch/semantic-version@v5.0.2
      id: versioning
      with:
         branch: main
         tag_prefix: "v"
         major_pattern: "MAJOR CHANGE:"
         minor_pattern: "MINOR CHANGE:"
         format: "v${major}.${minor}.${patch}-${increment}-$SERVICE"
         
    - uses: actions/checkout@v3
    - name: docker login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_HUB_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASS}}
        REPO_NAME: ${{secrets.REPO_NAME}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_HUB_USER}}/${{secrets.REPO_NAME}}:${{ steps.versioning.outputs.version }}
      
    - name: Push_Image
      run: docker push ${{secrets.DOCKER_HUB_USER}}/${{secrets.REPO_NAME}}:${{ steps.versioning.outputs.version }}
